version: "3.7"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
    - postgres
    image: faidapp_backend
    ports:
    - 3001:3001
    volumes: []
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on: []
    image: faidapp_frontend
    ports:
    - 3000:3000
    volumes: []
  postgres:
    depends_on: []
    env_file:
    - ./env/postgres.env
    image: postgres:11.5
    ports:
    - 5432:5432
    volumes: []
  strapi:
    build:
      context: ./strapi
      dockerfile: Dockerfile
    depends_on:
    - postgres
    env_file:
    - ./env/strapi.env
    image: faidapp_strapi
    ports:
    - 1337:1337
    volumes: []
volumes: {}
