FROM python:3

# update pip
RUN pip install --upgrade pip

# install dev pkg dependencies
RUN apt-get update && apt-get install -y \
    fish                ` # via :fish` \
    make                ` # via :makefile` \
    nano \
    postgresql-client   ` # via :dockerfile` \
    python3-pip         ` # via :dockerfile`

# install dev pip dependencies
RUN pip install \
    isort               ` # via :isort` \
    pip-tools           ` # via :pip-compile`

WORKDIR /app/src
