# Generated by Django 3.2.3 on 2021-05-19 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('models', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('modelclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.modelclass')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
            bases=('models.modelclass',),
        ),
    ]
