# Generated by Django 3.2.3 on 2021-05-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_hash',
            field=models.CharField(default='capoeira_52b403e578.jpg', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
