# Generated by Django 3.2.3 on 2021-05-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_image_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_props',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_hash',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
