FROM strapi/strapi

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

# install dev pkg dependencies
RUN apt-get update && apt-get install -y \
    fish                ` # via :fish` \
    make                ` # via :makefile` \
    nano                ` # via :dockerfile` \
    postgresql-client   ` # via :dockerfile` \
    python3-pip         ` # via :dockerfile`

# install dev pip dependencies
RUN pip3 install \
    pgcli==2.1.1        ` # via :dockerfile` \
    psycopg2-binary     ` # via :dockerfile`

WORKDIR /srv/app/src