FROM strapi/strapi

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

# install dev pkg dependencies
RUN apt-get update && apt-get install -y \
    fish                ` # via fish` \
    make                ` # via makefile` \
    nano                ` # via dockerfile` \
    postgresql-client   ` # via strapi`

RUN apt-get install -y python-pip

# install dev pip dependencies
RUN pip install \
    pgcli==2.1.1        ` # via strapi`

WORKDIR /srv/app/src