# Generated by Django 3.2.3 on 2021-05-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0002_auto_20210522_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
